on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test with params
    steps:
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@v0.1.17
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig-root: './src'
          max-size: 3
          orientation: LR
          debug: true
          in-details: true
          exclude: 'node_modules, test'
          include-index-file-dependencies: true
